---
driver_plugin: docker
driver_config:
  socket: tcp://localhost:4243
  provision_command: curl -L https://www.opscode.com/chef/install.sh | bash
  require_chef_omnibus: false
  ssh_gateway: ec2-54-211-97-92.compute-1.amazonaws.com
  username: coderanger
